### ISSUE TITLE
Issue when running /role-checker force-sync command

### ISSUE THREAD

**Issue by zacharytbaldino** [jonathonor/syncBot#18] opened 2022-11-26 04:44 UTC
Hello when running commands within a discord we are getting the following issues as well as an issue with "There was an error adding the role in the main server, see console for error.

syncbot ready!

    at async SequentialHandler.queueRequest (C:\Users\Administrator\Desktop\sync
bot\G3NSyncBot\syncBot\node_modules\@discordjs\rest\dist\index.js:458:14)
    at async REST.request (C:\Users\Administrator\Desktop\syncbot\G3NSyncBot\syn
cBot\node_modules\@discordjs\rest\dist\index.js:902:22)
    at async GuildMemberRoleManager.add (C:\Users\Administrator\Desktop\syncbot\
G3NSyncBot\syncBot\node_modules\discord.js\src\managers\GuildMemberRoleManager.j
s:131:7) {
  requestBody: { files: undefined, json: undefined },
  rawError: { message: 'Missing Permissions', code: 50013 },
  code: 50013,
  status: 403,
  method: 'PUT',
  url: 'https://discord.com/api/v10/guilds/633376696866963466/members/1030350259
601276929/roles/646101087044239372'
}
C:\Users\Administrator\Desktop\syncbot\G3NSyncBot\syncBot\node_modules\@discordj
s\rest\dist\index.js:659
        throw new DiscordAPIError(data, "code" in data ? data.code : data.error,
 status, method, url, requestData);
              ^

DiscordAPIError[50001]: Missing Access
    at SequentialHandler.runRequest (C:\Users\Administrator\Desktop\syncbot\G3NS
yncBot\syncBot\node_modules\@discordjs\rest\dist\index.js:659:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5
)
    at async SequentialHandler.queueRequest (C:\Users\Administrator\Desktop\sync
bot\G3NSyncBot\syncBot\node_modules\@discordjs\rest\dist\index.js:458:14)
    at async REST.request (C:\Users\Administrator\Desktop\syncbot\G3NSyncBot\syn
cBot\node_modules\@discordjs\rest\dist\index.js:902:22)
    at async GuildManager.fetch (C:\Users\Administrator\Desktop\syncbot\G3NSyncB
ot\syncBot\node_modules\discord.js\src\managers\GuildManager.js:273:20)
    at async addRole (file:///C:/Users/Administrator/Desktop/syncbot/G3NSyncBot/
syncBot/run.js:195:30) {
  requestBody: { files: undefined, json: undefined },
  rawError: { message: 'Missing Access', code: 50001 },
  code: 50001,
  status: 403,
  method: 'GET',
  url: 'https://discord.com/api/v10/guilds/830623778601304095?with_counts=true'
}

Node.js v18.3.0

Sometime while running the /role-checker command we get an error with Unable under issues with roleAnalyzeCallback

**Comment by jonathonor** [comment] 2022-12-08 18:07
Hi, this is a permissions issue. It could be a variety of different missing permissions.

Please make sure you have followed the documentation closely. 
I would suspect that the bot either is not above the role you are asking it to assign.

**Comment by zacharytbaldino** [comment] 2022-12-08 18:10
I will look into the bot on our end. It does also crash with Unknown Member also. Assuming this is also permission based? Would giving it server admin potentially resolve this issue?

**Comment by jonathonor** [comment] 2022-12-08 19:24
Unknown Member is a different issue I have dealt with in the past. Are you running the bot regular or in reverse?

**Comment by zacharytbaldino** [comment] 2022-12-08 19:29
The bot is running in regular mode, we are currently syncing a backup server with just staff on it. Don't know if that could also be throwing that issue. But it's only after a handful of unknown member alerts in our logs channel that it eventually stops

**Comment by jonathonor** [comment] 2022-12-08 19:45
Do you happen to know what's causing the Unknown Member error of have any logs? 

For example, is it when someone is added to the synced server, when someone leaves the main server etc...

I'll be looking into this.

**Comment by zacharytbaldino** [comment] 2022-12-08 19:50
It only seems to throw the error when a role is assigned to someone in the main that is not in the other. However I can monitor to see if it happens when someone joins when I am able to access. The VPS

**Comment by jonathonor** [comment] 2022-12-09 14:30
@zacharytbaldino I made many updates to the bot yesterday while working with a user in my discord server who was having a very similar issue to you. Please get the latest changes from github and let me know if you still run into the issue. If so we can diagnose further.

**Comment by zacharytbaldino** [comment] 2022-12-09 16:13
Just updated the bot. Everything seems to be working as it should, it does not crash when running the command and the bot now shows [bit name] is think with the dots and it hold steady for quite sometime. Don’t know if the bot has a timeout that makes it say the application didn’t respond (the server has 1000+) members in it. The console is not recognizing non manageable users and bots however

**Comment by zacharytbaldino** [comment] 2022-12-09 16:15
![BB3AA6A7-EC83-4B09-AFC6-E0EC3D42E1C6](https://user-images.githubusercontent.com/60193362/206745061-5887b95a-c005-4a8b-9fc2-83e8c474bb39.jpeg)

**Comment by jonathonor** [comment] 2022-12-09 17:32
The error you posted a screenshot of is not taking place in the role-checker command. 
Its actually caused by a user leaving the server, perhaps while the role-checker command is running....

I'll look into why it's failing nonetheless. I think I see the issue.

**Comment by jonathonor** [comment] 2022-12-09 17:45
@zacharytbaldino I have just pushed a fix for the issue you sent a screenshot of

**Comment by zacharytbaldino** [comment] 2022-12-09 17:56
![513BDE39-2854-47C2-A6B9-83BC7496D5EC](https://user-images.githubusercontent.com/60193362/206763509-008644e1-075d-4fe1-b870-f226e9ddecaa.jpeg)
Now receiving this issue on tuning node run.js I have not changed anything with the config file

**Comment by jonathonor** [comment] 2022-12-09 18:02
Do you still have a config.json file containing "applicationId" ?
Make sure when you updated the bot from github you did not lose it.

**Comment by zacharytbaldino** [comment] 2022-12-09 19:44
Mine contains, token and clientID

**Comment by jonathonor** [comment] 2022-12-09 20:41
Ah sorry. Changing clientId to applicationId should fix the issue.

**Comment by zacharytbaldino** [comment] 2022-12-09 20:48
Okay great, it seems to be working, I assume the bot in discord saying the application failed to respond is just a timeout on discords end as it throws it after about 30 mins but the bit is still running roleAnalyze

**Comment by zacharytbaldino** [comment] 2022-12-09 20:52
![image](https://user-images.githubusercontent.com/60193362/206794068-e1a0ec15-6df0-47af-afe6-ec31dacc4bd3.jpeg) I receive this crash after running analyze. If this may be something on my end.

**Comment by jonathonor** [comment] 2022-12-09 22:29
There is no way that the analyze should be taking 30 minutes. Likely the bot errores or something and never replied to the command.

I have never seen the unknown web hook error. 

Anything else in the logs?

**Comment by jonathonor** [comment] 2022-12-09 22:32
You can also run the bot now with
node run.js debug
To try and help you better find the issue.

**Comment by zacharytbaldino** [comment] 2022-12-09 23:29
I will run it with the debug and see what I can find I can also post the log when I get to a computer

**Comment by jonathonor** [comment] 2022-12-10 03:38
Ok I see. It appears that the bot only has 15 minutes to reply to the command. So if it's taking longer than that I'll need to send the message a different way. 

Is this happening on the role-checker analyze option? Or force-sync?

**Comment by zacharytbaldino** [comment] 2022-12-10 05:26
It happens on both options same error.

**Comment by jonathonor** [comment] 2022-12-10 13:58
Ok, I think I know how I'll fix it.

**Comment by jonathonor** [comment] 2022-12-10 23:45
I should have time to fix it Monday.

**Comment by zacharytbaldino** [comment] 2022-12-11 00:03
Take your time, sorry to throw all these issues at you

**Comment by jonathonor** [comment] 2022-12-11 00:43
No worries! I'm happy to help, and it makes the bot better for others who use it in the future!

**Comment by zacharytbaldino** [comment] 2022-12-13 00:54
Just wanted to throw this in here also, It looks like some of the errors that the console is throwing are related to something on our end as our backup server does not share roles as we have added some new roles

**Comment by jonathonor** [comment] 2022-12-13 13:14
No worries, I made some progress on fixes yesterday and am trying to wrap them up today, then I'll let you test them for me 🙂

**Comment by jonathonor** [comment] 2022-12-13 17:53
@zacharytbaldino Ok, I pushed an update that should allow the bot to process as many members as your guild has. Please run the role-checker with analyze option and report back if it works!

**Comment by zacharytbaldino** [comment] 2022-12-14 02:33
Just ran the command and it didn't throw any errors out of the norm, however I have not tested the force-sync function. I know before the update it ran just as an analyze and didn't update roles.

**Comment by jonathonor** [comment] 2022-12-19 17:18
Please verify that the functionality works as you expect and we can close this issue.

**Closed** 2023-01-12 16:12 UTC
